# This Python file uses the following encoding: utf-8
import sys
from pathlib import Path

from PySide6.QtGui import QGuiApplication
from PySide6.QtQml import QQmlApplicationEngine

# This file was auto-generated by QtCreator and is unchanged so far!
# Besides these two comment lines of course! ;)

button_data = [
    {
        "myText": "Click me Real!",
        "pointsToEnable": 0,
        "pointsPerClick": 1
    },
    {
        "myText": "Click me not?",
        "pointsToEnable": 50,
        "pointsPerClick": 10
    },
    {
        "myText": "Click me again!",
        "pointsToEnable": 250,
        "pointsPerClick": 50
    }
]


if __name__ == "__main__":
    # This is auto-generated by QtCreator
    app = QGuiApplication(sys.argv)
    engine = QQmlApplicationEngine()
    qml_file = Path(__file__).resolve().parent / "main.qml"


    context = engine.rootContext()
    context.setContextProperty("button_data_py", button_data)


    # This is auto-generated by QtCreator
    engine.load(qml_file)
    if not engine.rootObjects():
        sys.exit(-1)
    sys.exit(app.exec())
